# Generated by Django 4.2.5 on 2024-02-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0008_alter_draggableinput_x_axis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draggableinput',
            name='input_field_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
