# Generated by Django 4.2.5 on 2024-02-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0009_draggableinput_input_field_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='draggableinput',
            name='label_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
