# Generated by Django 4.2.5 on 2024-02-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0010_draggableinput_label_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draggableinput',
            name='label_id',
        ),
    ]
