# Generated by Django 4.2.5 on 2024-02-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0011_remove_draggableinput_label_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='draggableinput',
            name='label_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='draggableinput',
            name='label_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
