# Generated by Django 4.2.5 on 2024-02-27 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0011_draggableinput_label_x_axis_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DraggableInput',
        ),
    ]
