# Generated by Django 4.2.5 on 2024-02-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0012_draggableinput_label_id_draggableinput_label_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draggableinput',
            name='label_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='draggableinput',
            name='label_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
