# Generated by Django 4.2.5 on 2024-02-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0013_alter_draggableinput_label_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draggableinput',
            name='label_id',
        ),
        migrations.RemoveField(
            model_name='draggableinput',
            name='label_name',
        ),
    ]
