# Generated by Django 4.2.5 on 2024-02-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0014_remove_draggableinput_label_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draggableinput',
            name='label_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='draggableinput',
            name='label_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='draggableinput',
            name='label_x_axis',
            field=models.FloatField(default=''),
        ),
        migrations.AddField(
            model_name='draggableinput',
            name='label_y_axis',
            field=models.FloatField(default=''),
        ),
    ]
