# Generated by Django 4.2.5 on 2024-02-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0015_draggableinput_label_id_draggableinput_label_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draggableinput',
            name='label_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='draggableinput',
            name='label_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='draggableinput',
            name='label_x_axis',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='draggableinput',
            name='label_y_axis',
            field=models.FloatField(),
        ),
    ]
