# Generated by Django 4.2.5 on 2024-02-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0016_alter_draggableinput_label_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draggableinput',
            name='label_name',
            field=models.CharField(max_length=100),
        ),
    ]
