# Generated by Django 4.2.5 on 2024-02-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0017_alter_draggableinput_label_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draggableinput',
            name='label_x_axis',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='draggableinput',
            name='label_y_axis',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
