# Generated by Django 4.2.5 on 2024-02-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0018_alter_draggableinput_label_x_axis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draggableinput',
            name='label_x_axis',
        ),
        migrations.RemoveField(
            model_name='draggableinput',
            name='label_y_axis',
        ),
        migrations.AlterField(
            model_name='draggableinput',
            name='label_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='draggableinput',
            name='label_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
